# Generated by Django 4.2 on 2023-05-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confApp', '0005_auto_20230529_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='abstact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
