# Generated by Django 4.2 on 2023-05-30 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confApp', '0006_new_abstact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='abstact',
            new_name='new_abstract',
        ),
    ]
