# Generated by Django 4.2 on 2023-06-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confApp', '0007_rename_abstact_new_new_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='confApp.new'),
        ),
    ]
